/* The following code was generated by JFlex 1.4.3 on 3/12/13 10:49 PM */

/*
 * RuleTokenMaker.java - Token maker for the PRAISE rule language.
 * 
 * To generate this file, run:
 *     jflex /src/main/resources/com/sri/ai/praise/rules/rsyntaxtextarea/RuleTokenMaker.flex
 * 
 * Then delete the generated versions of yyreset(Reader) and zzRefill() so
 * that we use the versions defined in this file.  This will eliminate 
 * memory allocations.
 */
package com.sri.ai.praise.rules.rsyntaxtextarea;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.AbstractJFlexTokenMaker;
import org.fife.ui.rsyntaxtextarea.DefaultToken;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenMaker;


/**
 * Scanner for the PRAISE rule language.
 */

public class RuleTokenMaker extends AbstractJFlexTokenMaker implements TokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 4;
  public static final int YYINITIAL = 0;
  public static final int MLC = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\27\1\11\1\0\1\27\1\25\22\0\1\27\1\57\1\10"+
    "\1\26\1\33\1\35\1\32\1\7\1\56\1\56\1\31\1\34\1\64"+
    "\1\23\1\20\1\30\1\13\7\16\2\3\1\45\1\35\1\63\1\60"+
    "\1\62\1\32\1\26\4\17\1\22\1\17\3\2\1\24\7\2\1\6"+
    "\2\2\1\5\2\2\1\15\2\2\1\32\1\12\1\32\1\61\1\1"+
    "\1\0\1\47\1\52\1\17\1\51\1\21\1\42\1\2\1\36\1\43"+
    "\1\24\1\2\1\44\1\54\1\50\1\53\1\40\1\2\1\4\1\41"+
    "\1\37\1\5\1\2\1\46\1\14\1\55\1\2\3\25\1\32\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\3\2\2\4\1\5\1\3"+
    "\1\6\2\2\1\7\1\10\2\7\4\2\1\7\5\2"+
    "\1\11\2\1\1\2\1\12\1\13\5\12\1\14\3\12"+
    "\1\15\1\16\1\15\1\16\1\2\1\4\2\0\1\15"+
    "\1\3\1\15\2\2\1\17\1\20\7\2\1\0\1\21"+
    "\11\0\2\16\1\0\1\2\1\3\1\2\1\0\1\2"+
    "\10\0\1\16\2\2\1\22\2\0\1\23\2\0\1\24"+
    "\2\2\4\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\u01a8\0\u01dd\0\u0212\0\237\0\u0247\0\324\0\u027c\0\u02b1"+
    "\0\u02e6\0\u031b\0\u0350\0\237\0\u0385\0\u03ba\0\u03ef\0\u0424"+
    "\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\237\0\u0597"+
    "\0\u05cc\0\237\0\u0601\0\237\0\u0636\0\u066b\0\u06a0\0\u06d5"+
    "\0\u070a\0\237\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813\0\u0848"+
    "\0\u07de\0\u087d\0\237\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986"+
    "\0\u09bb\0\u09f0\0\237\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9"+
    "\0\u0b2e\0\u0b63\0\u0b98\0\u02e6\0\237\0\u0bcd\0\u0c02\0\u0c37"+
    "\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\237\0\u0daa"+
    "\0\u0ddf\0\u0e14\0\u0986\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d"+
    "\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b\0\u1090\0\u10c5"+
    "\0\u10fa\0\237\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203\0\u1238"+
    "\0\u126d\0\u12a2\0\u12d7\0\u1199\0\u130c\0\u1238";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\4\1\15\1\16\1\5\1\6\1\5\1\17"+
    "\1\20\1\5\1\21\1\5\2\4\1\22\1\23\1\24"+
    "\2\4\2\24\1\5\1\25\1\5\1\26\1\27\1\30"+
    "\1\5\1\31\1\5\1\32\1\33\1\5\1\34\1\35"+
    "\1\36\1\5\1\37\1\40\1\21\1\24\1\4\1\41"+
    "\1\42\11\43\1\44\17\43\1\45\4\43\1\46\3\43"+
    "\1\47\3\43\1\50\16\43\11\51\1\52\24\51\1\53"+
    "\3\51\1\54\3\51\1\55\16\51\66\0\6\5\4\0"+
    "\5\5\1\0\2\5\1\0\1\5\11\0\7\5\1\0"+
    "\10\5\7\0\3\56\1\6\3\56\3\0\1\56\1\6"+
    "\2\56\1\6\1\56\1\57\2\60\1\0\1\61\1\0"+
    "\1\56\4\0\1\56\2\0\7\56\1\0\10\56\10\0"+
    "\6\5\1\12\1\13\2\0\5\5\1\0\2\5\1\0"+
    "\1\5\11\0\7\5\1\0\1\5\1\62\6\5\10\0"+
    "\3\5\1\11\1\5\1\11\1\12\1\13\2\0\5\5"+
    "\1\0\2\5\1\0\1\5\11\0\7\5\1\0\10\5"+
    "\10\0\6\5\1\12\1\13\2\0\5\5\1\0\2\5"+
    "\1\0\1\5\11\0\7\5\1\0\10\5\7\0\7\12"+
    "\1\63\1\12\1\0\1\64\52\12\10\13\1\63\1\0"+
    "\1\65\52\13\3\56\1\66\3\56\3\0\1\56\1\67"+
    "\2\70\1\67\1\56\1\57\2\60\1\0\1\61\1\0"+
    "\1\56\4\0\1\56\2\0\7\56\1\0\10\56\12\0"+
    "\1\57\7\0\1\57\2\0\1\57\47\0\6\5\4\0"+
    "\1\5\1\71\3\5\1\0\2\5\1\0\1\5\11\0"+
    "\6\5\1\72\1\0\10\5\71\0\1\24\31\0\1\22"+
    "\65\0\1\73\1\74\34\0\6\5\4\0\5\5\1\0"+
    "\2\5\1\0\1\5\11\0\1\75\6\5\1\0\10\5"+
    "\10\0\6\5\4\0\5\5\1\0\2\5\1\0\1\5"+
    "\11\0\7\5\1\0\1\5\1\76\3\5\1\77\2\5"+
    "\10\0\6\5\4\0\5\5\1\0\2\5\1\0\1\5"+
    "\11\0\7\5\1\0\5\5\1\35\2\5\10\0\6\5"+
    "\4\0\5\5\1\0\2\5\1\0\1\5\11\0\4\5"+
    "\1\16\2\5\1\0\10\5\32\0\1\24\42\0\6\5"+
    "\4\0\5\5\1\0\2\5\1\0\1\5\11\0\3\5"+
    "\1\16\2\5\1\100\1\0\2\5\1\101\5\5\10\0"+
    "\6\5\4\0\5\5\1\0\2\5\1\0\1\5\11\0"+
    "\7\5\1\0\5\5\1\102\2\5\10\0\6\5\4\0"+
    "\5\5\1\0\1\16\1\5\1\0\1\5\11\0\7\5"+
    "\1\0\10\5\10\0\3\5\1\16\2\5\4\0\5\5"+
    "\1\0\2\5\1\0\1\5\11\0\7\5\1\0\10\5"+
    "\10\0\6\5\4\0\5\5\1\0\2\5\1\0\1\5"+
    "\11\0\7\5\1\0\1\5\1\103\6\5\67\0\1\24"+
    "\64\0\1\104\4\0\11\43\1\0\17\43\1\0\4\43"+
    "\1\0\3\43\1\0\3\43\1\0\16\43\30\0\1\105"+
    "\73\0\1\106\64\0\1\107\3\0\1\110\67\0\1\111"+
    "\16\0\11\51\1\0\24\51\1\0\3\51\1\0\3\51"+
    "\1\0\16\51\37\0\1\112\64\0\1\113\3\0\1\114"+
    "\67\0\1\115\16\0\7\56\3\0\6\56\1\0\2\56"+
    "\1\0\1\56\1\0\1\56\4\0\1\56\2\0\7\56"+
    "\1\0\10\56\12\0\1\57\7\0\1\57\2\0\1\57"+
    "\2\0\2\116\1\0\1\117\40\0\3\56\1\120\3\56"+
    "\3\0\1\56\1\120\2\56\1\120\1\56\1\0\2\56"+
    "\1\121\1\56\1\0\1\56\4\0\1\56\1\121\1\0"+
    "\7\56\1\0\10\56\10\0\6\5\4\0\5\5\1\0"+
    "\2\5\1\0\1\5\11\0\7\5\1\0\2\5\1\122"+
    "\5\5\7\0\11\12\1\0\53\12\11\13\1\0\53\13"+
    "\3\56\1\66\3\56\3\0\1\56\1\66\2\56\1\66"+
    "\1\56\1\57\2\60\1\0\1\61\1\0\1\56\4\0"+
    "\1\56\2\0\7\56\1\0\10\56\7\0\3\56\1\66"+
    "\3\56\3\0\1\56\1\67\2\56\1\67\1\56\1\57"+
    "\2\60\1\0\1\61\1\0\1\56\4\0\1\56\2\0"+
    "\7\56\1\0\10\56\7\0\3\56\1\123\3\56\3\0"+
    "\1\56\1\123\2\56\2\123\1\0\2\123\1\0\1\56"+
    "\1\0\1\56\4\0\1\56\2\0\4\56\1\123\2\56"+
    "\1\0\1\56\1\123\1\56\2\123\3\56\10\0\6\5"+
    "\4\0\5\5\1\0\2\5\1\0\1\5\11\0\5\5"+
    "\1\124\1\5\1\0\10\5\10\0\6\5\4\0\5\5"+
    "\1\0\2\5\1\0\1\5\11\0\3\5\1\34\3\5"+
    "\1\0\10\5\40\0\1\125\34\0\6\5\4\0\5\5"+
    "\1\0\1\126\1\5\1\0\1\5\11\0\7\5\1\0"+
    "\10\5\10\0\6\5\4\0\5\5\1\0\2\5\1\0"+
    "\1\5\11\0\7\5\1\0\6\5\1\34\1\5\10\0"+
    "\3\5\1\102\2\5\4\0\5\5\1\0\2\5\1\0"+
    "\1\5\11\0\7\5\1\0\10\5\10\0\6\5\4\0"+
    "\5\5\1\0\2\5\1\0\1\5\11\0\6\5\1\16"+
    "\1\0\10\5\10\0\6\5\4\0\5\5\1\0\2\5"+
    "\1\0\1\5\11\0\7\5\1\0\3\5\1\16\4\5"+
    "\10\0\6\5\4\0\5\5\1\0\2\5\1\0\1\5"+
    "\11\0\1\5\1\16\5\5\1\0\10\5\10\0\6\5"+
    "\4\0\5\5\1\0\2\5\1\0\1\5\11\0\7\5"+
    "\1\0\7\5\1\16\46\0\1\127\65\0\1\130\70\0"+
    "\1\131\66\0\1\132\55\0\1\133\65\0\1\134\70\0"+
    "\1\135\66\0\1\136\21\0\1\137\7\0\1\137\2\0"+
    "\1\137\4\0\1\121\10\0\1\121\30\0\3\56\1\120"+
    "\3\56\3\0\1\56\1\120\2\56\1\120\1\56\1\0"+
    "\2\56\1\0\1\61\1\0\1\56\4\0\1\56\2\0"+
    "\7\56\1\0\10\56\12\0\1\137\7\0\1\137\2\0"+
    "\1\137\47\0\6\5\4\0\5\5\1\0\2\5\1\0"+
    "\1\5\11\0\7\5\1\0\3\5\1\140\4\5\10\0"+
    "\6\5\4\0\5\5\1\0\2\5\1\0\1\5\11\0"+
    "\3\5\1\141\3\5\1\0\10\5\37\0\1\142\35\0"+
    "\3\5\1\34\2\5\4\0\5\5\1\0\2\5\1\0"+
    "\1\5\11\0\7\5\1\0\2\5\1\16\5\5\47\0"+
    "\1\143\71\0\1\144\40\0\1\130\63\0\1\145\104\0"+
    "\1\146\71\0\1\147\40\0\1\134\63\0\1\150\47\0"+
    "\1\137\7\0\1\137\2\0\1\137\5\0\1\117\41\0"+
    "\6\5\4\0\5\5\1\0\2\5\1\0\1\5\11\0"+
    "\7\5\1\0\5\5\1\151\2\5\10\0\6\5\4\0"+
    "\5\5\1\0\2\5\1\0\1\5\11\0\1\5\1\152"+
    "\5\5\1\0\10\5\50\0\1\130\3\0\1\144\47\0"+
    "\1\153\35\0\1\154\5\145\1\154\3\0\5\145\1\154"+
    "\2\145\1\154\1\145\1\0\1\154\1\0\1\145\2\154"+
    "\1\145\2\154\7\145\1\154\10\145\3\154\3\0\1\154"+
    "\41\0\1\134\3\0\1\147\47\0\1\155\35\0\1\156"+
    "\5\150\1\156\3\0\5\150\1\156\2\150\1\156\1\150"+
    "\1\0\1\156\1\0\1\150\2\156\1\150\2\156\7\150"+
    "\1\156\10\150\3\156\3\0\1\156\1\0\6\5\4\0"+
    "\5\5\1\0\2\5\1\0\1\5\11\0\7\5\1\0"+
    "\6\5\1\16\1\5\10\0\6\5\4\0\5\5\1\0"+
    "\2\5\1\0\1\5\11\0\3\5\1\16\3\5\1\0"+
    "\10\5\37\0\1\145\64\0\1\150\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4929];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\7\1\1\11\7\1\1\11\12\1\1\11"+
    "\2\1\1\11\1\1\1\11\5\1\1\11\10\1\1\11"+
    "\2\0\5\1\1\11\10\1\1\0\1\11\11\0\1\11"+
    "\1\1\1\0\3\1\1\0\1\1\10\0\3\1\1\11"+
    "\2\0\1\1\2\0\3\1\4\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
//  private int yyline;

  /** the number of characters up to the start of the matched text */
//  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
//  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
//  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
//  private boolean zzEOFDone;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public RuleTokenMaker() {
		super();
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *                    occurs.
	 */
	public void addToken(char[] array, int start, int end, int tokenType, int startOffset) {
		super.addToken(array, start,end, tokenType, startOffset);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return new String[] { "#", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {


		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
			case Token.COMMENT_MULTILINE:
				state = MLC;
				start = text.offset;
				break;
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		}
		catch (IOException ioe) {
			ioe.printStackTrace();
			return new DefaultToken();
		}

	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(java.io.Reader reader) throws java.io.IOException {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
//		zzAtBOL  = true;
		zzAtEOF  = false;
	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 * @exception   IOException  if any I/O-Error occurs.
	 */
	private boolean zzRefill() throws java.io.IOException {
		return zzCurrentPos>=s.offset+s.count;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public RuleTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public RuleTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 160) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { addNullToken(); return firstToken;
          }
        case 21: break;
        case 17: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+1, Token.COMMENT_MULTILINE);
          }
        case 22: break;
        case 18: 
          { addToken(Token.COMMENT_MULTILINE);
          }
        case 23: break;
        case 16: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 24: break;
        case 8: 
          { addToken(Token.WHITESPACE);
          }
        case 25: break;
        case 14: 
          { addToken(Token.LITERAL_NUMBER_FLOAT);
          }
        case 26: break;
        case 6: 
          { addToken(Token.RESERVED_WORD);
          }
        case 27: break;
        case 9: 
          { addToken(Token.SEPARATOR);
          }
        case 28: break;
        case 2: 
          { addToken(Token.IDENTIFIER);
          }
        case 29: break;
        case 12: 
          { addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 30: break;
        case 15: 
          { start = zzMarkedPos-2; yybegin(EOL_COMMENT);
          }
        case 31: break;
        case 1: 
          { addToken(Token.ERROR_IDENTIFIER);
          }
        case 32: break;
        case 4: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 33: break;
        case 20: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_EOL); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_EOL); start = zzMarkedPos;
          }
        case 34: break;
        case 19: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_MULTILINE); start = zzMarkedPos;
          }
        case 35: break;
        case 13: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 36: break;
        case 3: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 37: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 38: break;
        case 10: 
          { 
          }
        case 39: break;
        case 11: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 40: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
            case 111: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 112: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 113: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
